apiVersion: v1
kind: Pod
metadata:
    name: nginx-sample-app
        labels:
              app: nginx-sample-app
              spec:
                  containers:
                      - name: nginx
                            image: nginx
