apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPPrivilegedContainer
metadata: 
  name: psp-privileged-container
  annotations:
    # This constraint is not certified by CIS.
    description: "Restricts containers with `securityContext.privileged` set to `true`."
spec:
  enforcementAction: deny 
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    excludedNamespaces:
    - asm-system
    - kube-system
